services:
  mysql:
    ports:
      - '3307:3306'

  backend:
    env_file:
      - ./apps/backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile-dev
    ports:
      - '5173:5173'
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    env_file:
      - ./apps/frontend/.env
