server {
    listen 80;
    server_name localhost;

    # --- BẬT CẤU HÌNH NÉN GZIP TẠI ĐÂY ---
    gzip on;
    gzip_vary on;
    gzip_min_length 10240; # Chỉ nén các file lớn hơn 10KB
    gzip_proxied any;
    gzip_comp_level 6;     # Mức độ nén tối ưu (từ 1 đến 9, số 6 là cân bằng nhất giữa tốc độ và CPU)
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml application/json;
    gzip_disable "MSIE [1-6]\."; # Bỏ qua trình duyệt IE quá cổ lỗ sĩ
    # ------------------------------------

    # 1. Định cấu hình phục vụ file tĩnh và FIX LỖI 404 KHI F5 TRANG
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

        # Cấu hình lưu bộ nhớ đệm (Cache) cho các file tĩnh
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;

        # Lưu cache trong vòng 1 năm (31536000 giây)
        expires 1y;

        # Ra lệnh cho trình duyệt lưu công khai và không cần check lại với server
        add_header Cache-Control "public, no-transform, immutable";


        # Tắt log ghi nhận các file này để tránh làm đầy ổ cứng server
        access_log off;
        log_not_found off;
    }


    # 2. Cấu hình Proxy cho API (Bê nguyên logic rewrite từ Vite sang)
    location /api/ {
        proxy_pass http://equipment-rental-backend:8080/equipment_rental/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. Cấu hình Proxy cho WebSocket Chat (Bê nguyên logic từ Vite sang)
    location /ws-chat/ {
        proxy_pass http://equipment-rental-backend:8080/equipment_rental/ws-chat/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        # --- THÊM 2 DÒNG NÀY ĐỂ FIX LỖI 504 ---
        proxy_read_timeout 3600s; # Đợi người dùng gửi tin nhắn tối đa 1 tiếng (3600 giây)
        proxy_send_timeout 3600s; # Thời gian gửi dữ liệu tối đa 1 tiếng
        # --------------------------------------
    }
}
