import random
import string
from datetime import datetime
from pathlib import Path

# Danh sách tên Việt Nam
FIRST_NAMES_MALE = [
    "Minh", "Anh", "Hua", "Van", "Hung", "Dung", "Tung", "Khanh", "Dang", "Hoang",
    "Tuấn", "Thanh", "Phuc", "Long", "Binh", "Nam", "Khoi", "Khang", "Duc", "Nghia"
]

FIRST_NAMES_FEMALE = [
    "Trang", "Linh", "Chi", "Anh", "Huong", "Ngoc", "Yen", "Phuong", "Lan", "Hoa",
    "Thao", "Nhung", "Ha", "Van", "Kieu", "Mai", "Thu", "Tam", "Nhan", "Dieu"
]

LAST_NAMES = [
    "Nguyen", "Tran", "Le", "Pham", "Hoang", "Pham", "Vu", "Do", "Ho", "Ngoc",
    "Luong", "Ky", "Dang", "Bui", "Doan", "Nguyen", "Hoang", "Pham", "Luu", "Trinh"
]


def generate_random_email(first_name, last_name, index):
    domains = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com"]
    domain = random.choice(domains)
    return f"{first_name.lower()}.{last_name.lower()}{index}@{domain}"


def generate_random_phone():
    prefixes = ["090", "091", "093", "094", "096", "097", "098", "099", "032", "033", "034", "035", "038", "039"]
    return random.choice(prefixes) + ''.join(random.choices(string.digits, k=7))


def generate_id_card():
    return ''.join(random.choices(string.digits, k=12))


def hash_password(password):
    import bcrypt
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed.decode('utf-8')


def assign_roles(user_index):
    roles = []
    if user_index <= 5:
        roles.append("ADMIN")
    elif user_index <= 155:
        roles.append("OWNER")
        if random.random() < 0.3:
            roles.append("RENTER")
    else:
        roles.append("RENTER")
    return roles


def generate_users(num_users=1000):
    users = []
    user_roles = []

    for i in range(1, num_users + 1):
        is_male = random.choice([True, False])
        first_name = random.choice(FIRST_NAMES_MALE) if is_male else random.choice(FIRST_NAMES_FEMALE)
        last_name = random.choice(LAST_NAMES)
        full_name = f"{last_name} {first_name}"

        username = f"{first_name.lower()}.{last_name.lower()}{i}"
        email = generate_random_email(first_name, last_name, i)
        phone = generate_random_phone()
        id_card = generate_id_card()
        password_hashed = hash_password("Password@123")
        trust_score = round(random.uniform(3.00, 5.00), 2)
        enabled = i <= 950

        roles = assign_roles(i)

        users.append({
            'username': username,
            'full_name': full_name,
            'email': email,
            'phone': phone,
            'id_card': id_card,
            'password': password_hashed,
            'trust_score': trust_score,
            'enabled': str(enabled).upper()
        })

        for role in roles:
            user_roles.append({'user_id': i, 'role_name': role})

    return users, user_roles


def generate_users_sql(users):
    sql_lines = [
        "-- =====================================================",
        "-- SEED DATA: USERS",
        f"-- Total: {len(users)} users",
        f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "-- Password for all users: Password@123",
        "-- DO NOT EDIT THIS FILE MANUALLY - Regenerate with: python scripts/generate_users.py",
        "-- =====================================================",
        "",
        "INSERT INTO users (user_name, password, full_name, email, phone_number, id_card_number, trust_score, enabled) VALUES"
    ]

    values = []
    for user in users:
        value = f"""    ('{user['username']}', '{user['password']}', '{user['full_name']}', '{user['email']}', '{user['phone']}', '{user['id_card']}', {user['trust_score']}, {user['enabled']})"""
        values.append(value)

    sql_lines.append(",\n".join(values))
    sql_lines.append(";")

    return "\n".join(sql_lines)


def generate_user_roles_sql(user_roles, role_id_map):
    sql_lines = [
        "-- =====================================================",
        "-- SEED DATA: USER_ROLES",
        f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "-- =====================================================",
        "",
        "INSERT INTO user_roles (user_id, role_id) VALUES"
    ]

    values = []
    for ur in user_roles:
        role_id = role_id_map[ur['role_name']]
        values.append(f"    ({ur['user_id']}, {role_id})")

    sql_lines.append(",\n".join(values))
    sql_lines.append(";")
    return "\n".join(sql_lines)


def main():
    print("=" * 70)
    print("GENERATING SEED DATA FOR EQUIPMENT RENTAL WEBSITE")
    print("=" * 70)

    print("\nGenerating 1000 users...")
    users, user_roles = generate_users(1000)

    role_counts = {}
    for ur in user_roles:
        role_counts[ur['role_name']] = role_counts.get(ur['role_name'], 0) + 1

    print(f"\nRole distribution:")
    for role, count in sorted(role_counts.items()):
        percentage = count / len(users) * 100
        print(f"   {role:10s}: {count:4d} users ({percentage:5.1f}%)")

    user_role_counts = {}
    for ur in user_roles:
        user_role_counts[ur['user_id']] = user_role_counts.get(ur['user_id'], 0) + 1
    multi_role_users = sum(1 for count in user_role_counts.values() if count > 1)
    print(f"\nUsers with multiple roles: {multi_role_users}")

    role_id_map = {
        "ADMIN": 1,
        "OWNER": 2,
        "RENTER": 3
    }

    print("\nGenerating SQL statements...")
    users_sql = generate_users_sql(users)
    user_roles_sql = generate_user_roles_sql(user_roles, role_id_map)

    full_sql = f"""-- =====================================================
-- SEED DATA: USERS AND USER_ROLES
-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
-- DO NOT EDIT THIS FILE MANUALLY - Regenerate with: python scripts/generate_users.py
-- =====================================================

{users_sql}

{user_roles_sql}
"""

    # Output vào database/seed_users.sql (classpath:database/)
    backend_path = Path("src/main/resources/database")
    backend_path.mkdir(parents=True, exist_ok=True)

    output_file = backend_path / "seed_users.sql"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(full_sql)

    print(f"\nSuccessfully generated {len(users)} users!")
    print(f"Output file: {output_file}")
    print(f"\nDefault password for all users: Password@123")
    print(f"\nSpring Boot will auto-load this file on startup")
    print(f"(configured in application.yaml: spring.sql.init.data-locations)")
    print("\n" + "=" * 70)


if __name__ == "__main__":
    main()
