INSERT INTO roles (id, role_name, created_at, updated_at)
VALUES (1, 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, 'OWNER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'RENTER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
